### ISSUE TITLE
DLL Issue with AmazonSqs Repository

### ISSUE THREAD

**Issue by RPM1984** [brandonc/amazonsqs#1]
Looks like your repo is referencing directly the AWSSDK DLL in your lib folder (v1.3.50), which is different to the NuGet version that the core library (AmazonSqs) depends on.

So when i install via NuGet, i get an error saying AWSSDK v1.3.5.0 is not found.

So you need to remove the hardcoded dependency to AWSSDK in your lib folder, and replace it with a NuGet reference.

**Comment by luisrudge** [comment]
Do not close this. I cant use it via nuget too.
